#!/bin/bash

if [ -z "$1" ]; then
 	echo "Please provide a directory name"
  	exit 1
fi

dir=$1

mkdir -p "$dir"
cd "$dir" || exit

if [ -n "$2" ]; then
  	pkgName=$2
elif [ "$dir" = "." ]; then
  	pkgName=$(basename "$PWD")
else
  	pkgName="$dir"
fi

NIT_USER=${NIT_USER:-$(whoami)}
dots="$HOME/dotfiles/nit"

mkdir -p ".github/workflows"
mkdir -p "rusalka"
mkdir -p "src"

cp "$dots/.github/workflows/build.yml" ".github/workflows/build.yml"
cp "$dots/rusalka/build.ts" "rusalka/build.ts"
cp "$dots/src/index.ts" "src/index.ts"

cp "$dots/.gitignore" ".gitignore"
cp "$dots/suglite.json5" "suglite.json5"
cp "$dots/tsconfig.json" "tsconfig.json"

date=$(date +%Y) NIT_USER=$NIT_USER envsubst '$date $NIT_USER' < "$dots/LICENSE" > "LICENSE"
pkgName=$pkgName NIT_USER=$NIT_USER envsubst '$pkgName $NIT_USER' < "$dots/package.json" > "package.json"

bun install
bumr
